// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2mwLsg5pn_io09ZohB1XwXdogtowYfI',
    appId: '1:243912527227:web:874fce4ed8c66c4c8341de',
    messagingSenderId: '243912527227',
    projectId: 'voltix-1bac0',
    authDomain: 'voltix-1bac0.firebaseapp.com',
    databaseURL: 'https://voltix-1bac0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voltix-1bac0.firebasestorage.app',
    measurementId: 'G-X40TR6XQ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR4ln1TPX0oZVvmoRsNqQYYbFDR53L5Z4',
    appId: '1:243912527227:android:a784389b3eea7a528341de',
    messagingSenderId: '243912527227',
    projectId: 'voltix-1bac0',
    databaseURL: 'https://voltix-1bac0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voltix-1bac0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANLbhw4oVgIKDg5-F0HCYGb3M9Z0_hPjE',
    appId: '1:243912527227:ios:c810a5ada672719e8341de',
    messagingSenderId: '243912527227',
    projectId: 'voltix-1bac0',
    databaseURL: 'https://voltix-1bac0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voltix-1bac0.firebasestorage.app',
    iosBundleId: 'com.example.smartenergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANLbhw4oVgIKDg5-F0HCYGb3M9Z0_hPjE',
    appId: '1:243912527227:ios:c810a5ada672719e8341de',
    messagingSenderId: '243912527227',
    projectId: 'voltix-1bac0',
    databaseURL: 'https://voltix-1bac0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voltix-1bac0.firebasestorage.app',
    iosBundleId: 'com.example.smartenergy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW2mwLsg5pn_io09ZohB1XwXdogtowYfI',
    appId: '1:243912527227:web:15102971887a40378341de',
    messagingSenderId: '243912527227',
    projectId: 'voltix-1bac0',
    authDomain: 'voltix-1bac0.firebaseapp.com',
    databaseURL: 'https://voltix-1bac0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'voltix-1bac0.firebasestorage.app',
    measurementId: 'G-J0Q20S77MH',
  );
}
